//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors()
        {
            this.Appointments = new HashSet<Appointments>();
            this.Prescriptions = new HashSet<Prescriptions>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="FirstName boþ geçilemez")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "LastName boþ geçilemez")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Age boþ geçilemez")]
        public Nullable<int> Age { get; set; }
        [Display(Name ="DepartmanName")]
        [Required(ErrorMessage = "DepartmanName boþ geçilemez")]
        public Nullable<int> DepartmanId { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual Departmans Departmans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescriptions> Prescriptions { get; set; }
    }
}
