//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Prescriptions
    {
        public int Id { get; set; }
        [Display(Name ="DoctorName")]
        [Required(ErrorMessage = "DoctorName")]
        public Nullable<int> DoctorId { get; set; }
        [Required(ErrorMessage = "DoctorStatment")]
        public string DoctorStatment { get; set; }
        public Nullable<System.DateTime> PrescriptionsDate { get; set; }
    
        public virtual Doctors Doctors { get; set; }
    }
}
