//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sicks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sicks()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "FirstName boþ geçilemez")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "LastName boþ geçilemez")]
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [Required(ErrorMessage = "Tc boþ geçilemez")]
        public string Tc { get; set; }
        [Required(ErrorMessage = "Phone boþ geçilemez")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Homeland boþ geçilemez")]
        public string Homeland { get; set; }
        [Required(ErrorMessage = "FatherName boþ geçilemez")]
        public string FatherName { get; set; }
        [Required(ErrorMessage = "MotherName boþ geçilemez")]
        public string MotherName { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments> Appointments { get; set; }
    }
}
